### ISSUE TITLE
Issue in hosting

### ISSUE THREAD

**Issue by afoysal** [viralsolani/laravel-adminpanel#223]
I developed an application in my local Machine. It is working fine. But I host it in a Shared Hosting. I am getting below error there in `error.log` file.

```
[11-May-2018 13:53:53 UTC] PHP Warning:  Uncaught ErrorException: require(/home/foysal/Videos/bad-laravel-adminpanel/routes/breadcrumbs.php): failed to open stream: No such file or directory in /home/aylatddd/public_html/adminpanel/vendor/davejamesmiller/laravel-breadcrumbs/src/BreadcrumbsServiceProvider.php:92
Stack trace:
#0 /home/aylatddd/public_html/adminpanel/vendor/davejamesmiller/laravel-breadcrumbs/src/BreadcrumbsServiceProvider.php(92): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'require(/home/f...', '/home/aylatddd/...', 92, Array)
#1 /home/aylatddd/public_html/adminpanel/vendor/davejamesmiller/laravel-breadcrumbs/src/BreadcrumbsServiceProvider.php(92): require()
#2 /home/aylatddd/public_html/adminpanel/vendor/davejamesmiller/laravel-breadcrumbs/src/BreadcrumbsServiceProvider.php(61): DaveJamesMiller\Breadcrumbs\BreadcrumbsServiceProvider->registerBreadcrumbs()
#3 [internal function]: DaveJamesMiller\Breadcrumbs\BreadcrumbsServiceProvider->boot()
#4 /home/aylatddd/public_html/adminpanel/vendor/laravel/framework/src/Il in /home/aylatddd/public_html/adminpanel/vendor/davejamesmiller/laravel-breadcrumbs/src/BreadcrumbsServiceProvider.php on line 92
[11-May-2018 13:53:53 UTC] PHP Fatal error:  DaveJamesMiller\Breadcrumbs\BreadcrumbsServiceProvider::registerBreadcrumbs(): Failed opening required '/home/foysal/Videos/bad-laravel-adminpanel/routes/breadcrumbs.php' (include_path='.:/opt/alt/php71/usr/share/pear') in /home/aylatddd/public_html/adminpanel/vendor/davejamesmiller/laravel-breadcrumbs/src/BreadcrumbsServiceProvider.php on line 92
[11-May-2018 13:55:51 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /home/aylatddd/public_html/adminpanel/bootstrap/cache/config.php on line 487
```

**Comment by viralsolani** [comment]
@afoysal To install Laravel on Shared hosting you need to do some necessary settings on your server.

Please check these below tutorials

http://laraveldaily.com/laravel-and-shared-hosting-working-with-ftp-and-phpmyadmin/

https://medium.com/laravel-news/the-simple-guide-to-deploy-laravel-5-application-on-shared-hosting-1a8d0aee923e

This is not the issue of Laravel admin panel so closing this out.
