### ISSUE TITLE
Getting error for npm install command

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [viralsolani/laravel-adminpanel#364]
OS - Windows 10
PHP - 7.2.10

```
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ETIMEDOUT: request to https://registry.npmjs.org/parse-asn1 failed,reason: connect ETIMEDOUT 93.184.216.34:8080
npm WARN registry Using stale package data from https://registry.npmjs.org/ dueto a request error during revalidation.
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/array-flatten/-/array-flatten-2.1.1.tgz failed, reason: connect ETIMEDOUT 93.184.216.34:8080
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dell.DESKTOP-KU6707L\AppData\Roaming\npm-cache\_logs\2019-03-09T10_49_39_939Z-debug.log

```

**Comment by PrafullaKumarSahu** [comment]
Log 

```
14286 silly saveTree     `-- strip-json-comments@2.0.1
14287 verbose type system
14288 verbose stack FetchError: request to https://registry.npmjs.org/array-flatten/-/array-flatten-2.1.1.tgz failed, reason: connect ETIMEDOUT 93.184.216.34:8080
14288 verbose stack     at ClientRequest.req.on.err (C:\Users\Dell.DESKTOP-KU6707L\AppData\Roaming\npm\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
14288 verbose stack     at ClientRequest.emit (events.js:189:13)
14288 verbose stack     at onerror (C:\Users\Dell.DESKTOP-KU6707L\AppData\Roaming\npm\node_modules\npm\node_modules\agent-base\index.js:100:9)
14288 verbose stack     at callbackError (C:\Users\Dell.DESKTOP-KU6707L\AppData\Roaming\npm\node_modules\npm\node_modules\agent-base\index.js:122:5)
14288 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
14289 verbose cwd D:\work\www\laravel-adminpanel
14290 verbose Windows_NT 10.0.17134
14291 verbose argv "D:\\nodejs\\node.exe" "C:\\Users\\Dell.DESKTOP-KU6707L\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-f"
14292 verbose node v10.15.3
14293 verbose npm  v6.5.0
14294 error code ETIMEDOUT
14295 error errno ETIMEDOUT
14296 error network request to https://registry.npmjs.org/array-flatten/-/array-flatten-2.1.1.tgz failed, reason: connect ETIMEDOUT 93.184.216.34:8080
14297 error network This is a problem related to network connectivity.
14297 error network In most cases you are behind a proxy or have bad network settings.
14297 error network
14297 error network If you are behind a proxy, please make sure that the
14297 error network 'proxy' config is set properly.  See: 'npm help config'
14298 verbose exit [ 1, true ]
```

**Comment by bvipul** [comment]
"This is a problem related to network connectivity"
Just extracted above line from your log. Maybe you are doing this at your work, and it has some kind of proxy enabled.

**Comment by PrafullaKumarSahu** [comment]
@bvipul  I tried using 3 networks and got the same error in all and among them, one is a mobile connection.

**Comment by viralsolani** [comment]
I've just pushed the latest changes. please check once again and let us know if issue still persists
